language: java
jdk:
  - openjdk8

script: ./mvnw clean install
script: ./mvnw -Pfull clean install


jobs:
  include:
    - stage: Test
      script: ./mvnw clean test

notification:
  email: info@techprimers.com
